(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};m[i].l=1*new Date();for(var j=0;j<document.scripts.length;j++){if(document.scripts[j].src===r){return;}}k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a);})(window,document,'script','https://mc.yandex.ru/metrika/tag.js?id=111542280','ym');
ym(111542280,'init',{ssr:true,webvisor:true,clickmap:true,ecommerce:'dataLayer',accurateTrackBounce:true,trackLinks:true});

document.addEventListener('DOMContentLoaded',function(){
  if(!/ventricular-arrhythmias\.html$/.test(location.pathname)) return;
  const add=(sectionId,html)=>{const s=document.getElementById(sectionId);if(!s||s.querySelector('.va-supplement'))return;const d=document.createElement('div');d.className='va-supplement';d.innerHTML=html;s.appendChild(d)};
  add('diagnostics',`<h3>Дополнительные клинические акценты</h3><ul><li><b>После необъяснимой остановки кровообращения</b> обследование не должно завершаться на нормальной ЭхоКГ или отсутствии обструктивной ИБС: необходим последовательный поиск структурного и первичного электрического заболевания с использованием МРТ сердца, провокационных/нагрузочных тестов и генетической оценки по показаниям.</li><li><b>Семейный анамнез:</b> при подозрении на наследственное заболевание целесообразно собирать родословную как минимум за 3 поколения с уточнением внезапной смерти, необъяснимых синкопе, эпилепсии, утопления, внезапной смерти во сне и ранней имплантации ICD/ЭКС.</li><li><b>Генетика:</b> выявление вероятно патогенного/патогенного варианта у пробанда должно сопровождаться генетическим консультированием и, когда это уместно, каскадным обследованием родственников.</li></ul>`);
  add('classification',`<h3>Практическое разделение по этиологии</h3><div class="callout"><b>После определения формы аритмии задайте второй вопрос: какой субстрат?</b> Ишемический/рубцовый, кардиомиопатия, воспалительное заболевание, первичное электрическое заболевание или идиопатическая ЖА. Это разделение определяет прогноз, необходимость семейного обследования и выбор между медикаментозной терапией, аблацией и ICD.</div>`);
  add('treatment',`<h3>Дополнительные возможности при высоком риске</h3><ul><li><b>Электрический шторм:</b> практическое определение — ≥3 эпизодов устойчивой ЖА за 24 часа, разделённых во времени и требующих вмешательства для прекращения. Помимо антиаритмической терапии и коррекции триггеров важны снижение симпатической активации, оптимизация программирования ICD и ранняя оценка возможности аблации.</li><li><b>Подкожный ICD (S-ICD)</b> может рассматриваться у отдельных пациентов, которым нужна дефибрилляторная защита, но не требуется постоянная брадикардитическая стимуляция, CRT или антитахикардитическая стимуляция; выбор системы должен быть индивидуальным.</li><li><b>Носимый кардиовертер-дефибриллятор (WCD)</b> — временная стратегия для отдельных пациентов с преходящим/ещё не определённым риском ВСС, когда постоянный ICD пока не показан или временно невозможен; не является рутинной заменой ICD.</li><li><b>Кардиальная симпатическая денервация</b> может рассматриваться в специализированном центре при рефрактерных желудочковых аритмиях в отдельных клинических сценариях, особенно когда сохраняются рецидивы несмотря на оптимальную терапию и/или аблацию.</li></ul>`);
  add('discharge',`<h3>После ICD или катетерной аблации</h3><ul><li><b>После ICD:</b> до выписки проверить устройство и зоны детекции/терапии, дать пациенту план очного или дистанционного контроля и объяснить действия при одиночном и множественных разрядах.</li><li><b>После аблации ЖТ:</b> зафиксировать клиническую ЖТ и выполненный субстрат/мишень, план антиаритмической терапии, сроки контроля ритма и устройства; аблация уменьшает рецидивы, но сама по себе не отменяет показания к ICD, если они сохраняются.</li><li><b>Семейный скрининг:</b> если выявлена наследственная кардиомиопатия/каналопатия или остаётся обоснованное подозрение на неё, в выписке должен быть отдельный план обследования родственников первой линии.</li></ul>`);
});

document.addEventListener('DOMContentLoaded',function(){
  const box=document.getElementById('prevent'); if(!box) return;
  box.innerHTML=`
  <div class="calc-head"><div><h2>PREVENT</h2><p class="desc">AHA PREVENT — оценка 10- и 30-летнего сердечно-сосудистого риска в первичной профилактике.</p></div><span class="badge">СС-РИСК</span></div>
  <p class="interpret">PREVENT выдаёт не сумму баллов, а прогнозируемый риск события в процентах. Все показатели холестерина вводятся в ммоль/л.</p>
  <div class="fields">
    <div class="field"><label>Возраст, лет</label><p class="hint">30–79 лет; 30-летний прогноз — 30–59 лет.</p><input id="pAge" type="number" min="30" max="79" placeholder="55"></div>
    <div class="field"><label>Пол</label><select id="pSex"><option value="male">Мужчина</option><option value="female">Женщина</option></select></div>
    <div class="field"><label>Общий холестерин, ммоль/л</label><p class="hint">Допустимый диапазон PREVENT: 3,36–8,28 ммоль/л.</p><input id="pTc" type="number" step="0.01" min="3.36" max="8.28" placeholder="5.17"></div>
    <div class="field"><label>ХС-ЛВП, ммоль/л</label><p class="hint">Допустимый диапазон PREVENT: 0,52–2,59 ммоль/л.</p><input id="pHdl" type="number" step="0.01" min="0.52" max="2.59" placeholder="1.16"></div>
    <div class="field"><label>САД, мм рт. ст.</label><input id="pSbp" type="number" min="90" max="180" placeholder="130"></div>
    <div class="field"><label>ИМТ, кг/м²</label><input id="pBmi" type="number" step="0.1" min="18.5" max="39.9" placeholder="27.0"></div>
    <div class="field"><label>рСКФ, мл/мин/1,73 м²</label><input id="pEgfr" type="number" min="15" max="140" placeholder="90"></div>
    <div class="field"><label>Факторы / терапия</label><label class="check"><input id="pSmoke" type="checkbox">Курит сейчас</label><label class="check"><input id="pDm" type="checkbox">Сахарный диабет</label><label class="check"><input id="pBpTx" type="checkbox">Антигипертензивная терапия</label><label class="check"><input id="pStatin" type="checkbox">Статин</label></div>
  </div>
  <div class="actions"><button id="pCalc">Рассчитать PREVENT</button><button id="pClear" class="clear">Очистить</button><button id="pExample" class="clear">Проверочный пример</button></div>
  <div id="pStatus" class="interpret">Подготовка расчётного модуля…</div><div id="pRes" class="res">Введите параметры пациента.</div>
  <div class="interpret" style="margin-top:18px;padding:14px;border:1px solid #e5e9ef;border-radius:10px;background:#f8fafc"><b>Категории итогового 10-летнего PREVENT-ASCVD результата:</b><br>• <b>&lt;3%</b> — низкий риск<br>• <b>3–&lt;5%</b> — пограничный риск<br>• <b>5–&lt;10%</b> — промежуточный риск<br>• <b>≥10%</b> — высокий риск<br><br><span class="hint">Это категории именно для 10-летнего PREVENT-ASCVD. PREVENT-CVD и PREVENT-HF являются отдельными прогнозами и не классифицируются по этой таблице.</span></div>
  <div class="interpret" style="margin-top:14px"><b>Клинический смысл категорий PREVENT-ASCVD:</b><br><b>Низкий (&lt;3%)</b> — акцент на образ жизни и контроль факторов риска.<br><b>Пограничный (3–&lt;5%)</b> — липидснижающую терапию можно рассматривать после обсуждения дополнительных факторов риска.<br><b>Промежуточный (5–&lt;10%)</b> — липидснижающую терапию следует рассмотреть; обычно как минимум умеренной интенсивности.<br><b>Высокий (≥10%)</b> — выраженный риск; при показаниях рекомендуется интенсивная липидснижающая терапия и более строгие цели ХС-ЛНП.</div>
  <p class="interpret"><b>CVD</b> — общий сердечно-сосудистый риск; <b>ASCVD</b> — атеросклеротические события; <b>HF</b> — сердечная недостаточность; дополнительно показываются CHD и инсульт. Эти проценты нельзя складывать.</p><p class="interpret"><b>Важно:</b> PREVENT применяется для первичной профилактики и не заменяет клиническую оценку.</p>`;

  const el=id=>document.getElementById(id), num=id=>Number(el(id).value), chk=id=>el(id).checked;
  const pct=x=>(Number(x)*100).toFixed(1).replace('.',',')+'%';
  const category=x=>{x=Number(x)*100;return x<3?'низкий':x<5?'пограничный':x<10?'промежуточный':'высокий'};
  const render=(years,o)=>`<div style="margin-top:12px;border:1px solid #dfe5ec;border-radius:10px;padding:12px;background:#fff"><b>${years}-летний риск</b><br>CVD: <b>${pct(o.total_cvd)}</b> · ASCVD: <b>${pct(o.ascvd)}</b>${years===10?' <span style="font-weight:700">— '+category(o.ascvd)+' риск</span>':''} · HF: <b>${pct(o.heart_failure)}</b><br>CHD: ${pct(o.chd)} · Инсульт: ${pct(o.stroke)}</div>`;
  let webR=null,ready=false,loading=null;
  async function init(){if(ready)return;if(loading)return loading;el('pCalc').disabled=true;el('pStatus').textContent='Загружаю модуль PREVENT…';loading=(async()=>{const mod=await import('https://webr.r-wasm.org/latest/webr.mjs');webR=new mod.WebR({interactive:false});await webR.init();await webR.installPackages(['preventr']);await webR.evalRVoid('suppressPackageStartupMessages(library(preventr))');ready=true;el('pCalc').disabled=false;el('pStatus').textContent='✓ PREVENT готов к расчёту.'})().catch(err=>{console.error(err);el('pStatus').textContent='Не удалось загрузить расчётный модуль. Обновите страницу.';el('pCalc').disabled=false;throw err});return loading}
  function validate(){const a=num('pAge'),tc=num('pTc'),hdl=num('pHdl'),sbp=num('pSbp'),bmi=num('pBmi'),egfr=num('pEgfr'),e=[];if(!(a>=30&&a<=79))e.push('возраст 30–79 лет');if(!(tc>=3.36&&tc<=8.28))e.push('общий холестерин 3,36–8,28 ммоль/л');if(!(hdl>=0.52&&hdl<=2.59))e.push('ХС-ЛВП 0,52–2,59 ммоль/л');if(!(sbp>=90&&sbp<=180))e.push('САД 90–180 мм рт. ст.');if(!(bmi>=18.5&&bmi<=39.9))e.push('ИМТ 18,5–39,9 кг/м²');if(!(egfr>=15&&egfr<=140))e.push('рСКФ 15–140 мл/мин/1,73 м²');return e}
  el('pClear').onclick=()=>{['pAge','pTc','pHdl','pSbp','pBmi','pEgfr'].forEach(id=>el(id).value='');['pSmoke','pDm','pBpTx','pStatin'].forEach(id=>el(id).checked=false);el('pSex').value='male';el('pRes').innerHTML='Введите параметры пациента.'};
  el('pExample').onclick=()=>{el('pAge').value=50;el('pSex').value='female';el('pTc').value=5.17;el('pHdl').value=1.16;el('pSbp').value=160;el('pBmi').value=35;el('pEgfr').value=90;el('pSmoke').checked=false;el('pDm').checked=true;el('pBpTx').checked=true;el('pStatin').checked=false;el('pRes').innerHTML='Проверочный профиль загружен. Нажмите «Рассчитать PREVENT».'};
  el('pCalc').onclick=async()=>{const problems=validate();if(problems.length){el('pRes').innerHTML='<b>Проверьте данные:</b><br>• '+problems.join('<br>• ');return}try{await init();const age=num('pAge'),sex=el('pSex').value,sbp=num('pSbp'),tc=num('pTc'),hdl=num('pHdl'),bmi=num('pBmi'),egfr=num('pEgfr');const code=`x<-estimate_risk(age=${age},sex='${sex}',sbp=${sbp},bp_tx=${chk('pBpTx')?'TRUE':'FALSE'},total_c=${tc},hdl_c=${hdl},statin=${chk('pStatin')?'TRUE':'FALSE'},dm=${chk('pDm')?'TRUE':'FALSE'},smoking=${chk('pSmoke')?'TRUE':'FALSE'},egfr=${egfr},bmi=${bmi},model='base',time='both',chol_unit='mmol/L',quiet=TRUE); paste(c(x$risk_est_10yr$total_cvd,x$risk_est_10yr$ascvd,x$risk_est_10yr$heart_failure,x$risk_est_10yr$chd,x$risk_est_10yr$stroke,x$risk_est_30yr$total_cvd,x$risk_est_30yr$ascvd,x$risk_est_30yr$heart_failure,x$risk_est_30yr$chd,x$risk_est_30yr$stroke),collapse='|')`;const r=await webR.evalRString(code),v=String(r).split('|').map(Number),ten={total_cvd:v[0],ascvd:v[1],heart_failure:v[2],chd:v[3],stroke:v[4]};let html=render(10,ten);if(age<=59){html+=render(30,{total_cvd:v[5],ascvd:v[6],heart_failure:v[7],chd:v[8],stroke:v[9]})}else html+='<div class="hint" style="margin-top:10px">30-летний риск для возраста старше 59 лет не выводится.</div>';el('pRes').innerHTML=html}catch(err){console.error(err);el('pRes').innerHTML='<b>Ошибка расчёта.</b><br>Обновите страницу и попробуйте ещё раз.'}};
  init();
});